version: "3.8"

services:
  postgres:
    image: postgres:16-alpine
    container_name: postgres_db
    restart: unless-stopped
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-winwin}
      POSTGRES_USER: ${POSTGRES_USER:-winwin}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-winwin1234}
    volumes:
      - pg_data:/var/lib/postgresql/data
      - ./db/sql:/docker-entrypoint-initdb.d:ro
      - ./db/data:/data
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "${POSTGRES_USER:-winwin}" ]
      interval: 5s
      retries: 5
    command: >
      postgres
      -c max_connections=200
      -c shared_buffers=256MB

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    restart: unless-stopped
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "${PGADMIN_PORT:-8080}:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL:-winwin@example.com}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD:-winwin1234}
      PGADMIN_CONFIG_SERVER_MODE: "False"
      PGADMIN_CONFIG_MASTER_PASSWORD_REQUIRED: "False"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
      - ./pgadmin/servers.json:/pgadmin4/servers.json:ro
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost/pgadmin4/" ]
      interval: 10s
      retries: 5

volumes:
  pg_data:
  pgadmin_data:
